const searchData = {
  data: [
    {
      score: 0.7319644,
      show: {
        id: 62694,
        url: "https://www.tvmaze.com/shows/62694/go",
        name: "GO",
        type: "Game Show",
        language: "English",
        genres: [],
        status: "Ended",
        runtime: 30,
        averageRuntime: null,
        premiered: "1983-10-03",
        ended: "1983-10-07",
        officialSite: null,
        schedule: {
          time: "",
          days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        },
        rating: { average: null },
        weight: 3,
        network: {
          id: 1,
          name: "NBC",
          country: {
            name: "United States",
            code: "US",
            timezone: "America/New_York",
          },
          officialSite: "https://www.nbc.com/",
        },
        webChannel: null,
        dvdCountry: null,
        externals: { tvrage: null, thetvdb: 74213, imdb: "tt0198132" },
        image: null,
        summary:
          "<p><b>GO</b> is created by Bob Stewart, and is a spin off of his Chain Reaction game show. In Chain Reaction, the two teams (including panellists) had to complete the words that have things in common with each other. The bonus round is timed, with people taking turns one word at a time, finishing the sentence, ringing the bell, until the other team member got all the questions answered correctly. This bonus round is Go's regular rounds. Go created a new bonus round where one team member is surrounded by all of them. After each correct answer, one team member sits out until there is one other team member left (and can ask the question without interruption). If there is time left, the other team members slowly return. Johnny Gilbert returned to announce GO. However, it was hosted by Kevin O'Connell. You ought to be able to remember this game show. The title is short, and all over the stage, at least 27 times. The textured patterns you see on the letters are chains, to celebrate its Chain Reaction heritage.</p>",
        updated: 1656207332,
        _links: {
          self: { href: "https://api.tvmaze.com/shows/62694" },
          previousepisode: { href: "https://api.tvmaze.com/episodes/2352470" },
        },
      },
    },
    {
      score: 0.6650132,
      show: {
        id: 230,
        url: "https://www.tvmaze.com/shows/230/go-on",
        name: "Go On",
        type: "Scripted",
        language: "English",
        genres: ["Comedy"],
        status: "Ended",
        runtime: 30,
        averageRuntime: 30,
        premiered: "2012-08-08",
        ended: "2013-04-11",
        officialSite: null,
        schedule: { time: "21:30", days: ["Thursday"] },
        rating: { average: 7 },
        weight: 49,
        network: {
          id: 1,
          name: "NBC",
          country: {
            name: "United States",
            code: "US",
            timezone: "America/New_York",
          },
          officialSite: "https://www.nbc.com/",
        },
        webChannel: null,
        dvdCountry: null,
        externals: { tvrage: 30756, thetvdb: 258616, imdb: "tt2300923" },
        image: {
          medium:
            "https://static.tvmaze.com/uploads/images/medium_portrait/1/3773.jpg",
          original:
            "https://static.tvmaze.com/uploads/images/original_untouched/1/3773.jpg",
        },
        summary:
          "<p>Following the sudden death of his wife, sports radio personality Ryan King is forced to attend grief counseling. Feeling it unnecessary, he does so reluctantly, and with minimal participation, until it becomes clear that this may actually help him in unexpected ways.</p>",
        updated: 1637569035,
        _links: {
          self: { href: "https://api.tvmaze.com/shows/230" },
          previousepisode: { href: "https://api.tvmaze.com/episodes/14615" },
        },
      },
    },
    {
      score: 0.662585,
      show: {
        id: 24658,
        url: "https://www.tvmaze.com/shows/24658/go-fish",
        name: "Go Fish",
        type: "Scripted",
        language: "English",
        genres: ["Comedy", "Romance"],
        status: "Ended",
        runtime: 30,
        averageRuntime: 30,
        premiered: "2001-06-19",
        ended: "2001-07-03",
        officialSite: null,
        schedule: { time: "20:30", days: ["Tuesday"] },
        rating: { average: null },
        weight: 47,
        network: {
          id: 1,
          name: "NBC",
          country: {
            name: "United States",
            code: "US",
            timezone: "America/New_York",
          },
          officialSite: "https://www.nbc.com/",
        },
        webChannel: null,
        dvdCountry: null,
        externals: { tvrage: null, thetvdb: 289996, imdb: "tt0271288" },
        image: {
          medium:
            "https://static.tvmaze.com/uploads/images/medium_portrait/94/235738.jpg",
          original:
            "https://static.tvmaze.com/uploads/images/original_untouched/94/235738.jpg",
        },
        summary:
          "<p>High school freshman Andy \"Fish\" Troutner hopes to join the cool crowd as he enters high school. But the lovestruck Fish's most difficult hurdle will be to catch the attention of the beautiful Jess Riley -- who barely knows he exists. Trying to establish their own footholds in the high school hierarchy are his friends, heavy-set Henry Krakowski and the blissfully oblivious Hazard. Also populating Fish's world: his eccentris parents; his older brother Pete, a recent college grad who has joined the teaching staff; oddball drama teacher Mr. Hopkins; and attractive English teacher Miss Eastwood.</p>",
        updated: 1485054734,
        _links: {
          self: { href: "https://api.tvmaze.com/shows/24658" },
          previousepisode: { href: "https://api.tvmaze.com/episodes/1046713" },
        },
      },
    },
    {
      score: 0.6621067,
      show: {
        id: 56424,
        url: "https://www.tvmaze.com/shows/56424/van-go",
        name: "Van Go",
        type: "Reality",
        language: "English",
        genres: ["DIY"],
        status: "Running",
        runtime: null,
        averageRuntime: 25,
        premiered: "2021-02-12",
        ended: null,
        officialSite:
          "https://magnolia.com/watch/show/05f58ef5-d2f1-5274-823e-895af3c39e8c/van-go/",
        schedule: { time: "", days: ["Friday"] },
        rating: { average: null },
        weight: 46,
        network: null,
        webChannel: {
          id: 460,
          name: "Magnolia Network",
          country: {
            name: "United States",
            code: "US",
            timezone: "America/New_York",
          },
          officialSite: "https://magnolia.com/network/",
        },
        dvdCountry: null,
        externals: { tvrage: null, thetvdb: 399484, imdb: "tt14022916" },
        image: {
          medium:
            "https://static.tvmaze.com/uploads/images/medium_portrait/410/1027407.jpg",
          original:
            "https://static.tvmaze.com/uploads/images/original_untouched/410/1027407.jpg",
        },
        summary:
          "<p>Chewy Design Co. owner Brett Lewis renovates vans into tiny homes on the road, innovating creative solutions and tackling the many challenges that come with custom outfitting each vehicle for his clients' lifestyles.</p>",
        updated: 1658611507,
        _links: {
          self: { href: "https://api.tvmaze.com/shows/56424" },
          previousepisode: { href: "https://api.tvmaze.com/episodes/2319178" },
        },
      },
    },
    {
      score: 0.658606,
      show: {
        id: 16732,
        url: "https://www.tvmaze.com/shows/16732/fair-go",
        name: "Fair Go",
        type: "News",
        language: "English",
        genres: [],
        status: "Running",
        runtime: 30,
        averageRuntime: 30,
        premiered: "1977-04-07",
        ended: null,
        officialSite: "http://tvnz.co.nz/fair-go",
        schedule: { time: "19:30", days: ["Monday"] },
        rating: { average: null },
        weight: 44,
        network: {
          id: 1031,
          name: "TVNZ 1",
          country: {
            name: "New Zealand",
            code: "NZ",
            timezone: "Pacific/Auckland",
          },
          officialSite: "https://www.tvnz.co.nz/",
        },
        webChannel: null,
        dvdCountry: null,
        externals: { tvrage: 32298, thetvdb: 269546, imdb: "tt0191686" },
        image: {
          medium:
            "https://static.tvmaze.com/uploads/images/medium_portrait/376/942307.jpg",
          original:
            "https://static.tvmaze.com/uploads/images/original_untouched/376/942307.jpg",
        },
        summary:
          '<p>A long-running New Zealand programme in which a team of presenters investigate issues and complaints relating to "consumer rights".</p>',
        updated: 1661728827,
        _links: {
          self: { href: "https://api.tvmaze.com/shows/16732" },
          previousepisode: { href: "https://api.tvmaze.com/episodes/2381823" },
        },
      },
    },
    {
      score: 0.6578192,
      show: {
        id: 39025,
        url: "https://www.tvmaze.com/shows/39025/lets-go",
        name: "Let's Go!",
        type: "Scripted",
        language: "Korean",
        genres: ["Drama", "Comedy"],
        status: "Ended",
        runtime: 35,
        averageRuntime: 35,
        premiered: "2002-03-18",
        ended: "2002-04-26",
        officialSite: "http://tv.sbs.co.kr/letsgo/",
        schedule: {
          time: "18:35",
          days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        },
        rating: { average: null },
        weight: 43,
        network: {
          id: 127,
          name: "SBS",
          country: {
            name: "Korea, Republic of",
            code: "KR",
            timezone: "Asia/Seoul",
          },
          officialSite: null,
        },
        webChannel: null,
        dvdCountry: null,
        externals: { tvrage: null, thetvdb: null, imdb: null },
        image: null,
        summary: null,
        updated: 1539109720,
        _links: {
          self: { href: "https://api.tvmaze.com/shows/39025" },
          previousepisode: { href: "https://api.tvmaze.com/episodes/1543873" },
        },
      },
    },
    {
      score: 0.6523556,
      show: {
        id: 9614,
        url: "https://www.tvmaze.com/shows/9614/go-girls",
        name: "Go Girls",
        type: "Scripted",
        language: "English",
        genres: ["Drama", "Comedy"],
        status: "Ended",
        runtime: 60,
        averageRuntime: 60,
        premiered: "2009-02-19",
        ended: "2013-07-16",
        officialSite: null,
        schedule: { time: "20:45", days: ["Tuesday"] },
        rating: { average: null },
        weight: 39,
        network: {
          id: 452,
          name: "TVNZ 2",
          country: {
            name: "New Zealand",
            code: "NZ",
            timezone: "Pacific/Auckland",
          },
          officialSite: "https://www.tvnz.co.nz/livetv/tvnz-2",
        },
        webChannel: null,
        dvdCountry: null,
        externals: { tvrage: 21940, thetvdb: 132271, imdb: "tt1386958" },
        image: {
          medium:
            "https://static.tvmaze.com/uploads/images/medium_portrait/33/83812.jpg",
          original:
            "https://static.tvmaze.com/uploads/images/original_untouched/33/83812.jpg",
        },
        summary:
          "<p>Rich, famous and married… in just 365 days and counting. Amy, Britta and Cody are three young women suffering their quarter century crisis: 25 and what have they achieved? At the end of their worst week ever, the girls make a vow that in one year, Amy will be rich, Britta famous and Cody married. Their mate-since-childhood Kevin, admires their pluck but, to be honest, since Amy, Britta and Cody are currently Tragically Poor; Tragically Unknown; and Tragically Single, he reckons it's going to be a bit of an ask.</p>",
        updated: 1603562800,
        _links: {
          self: { href: "https://api.tvmaze.com/shows/9614" },
          previousepisode: { href: "https://api.tvmaze.com/episodes/516577" },
        },
      },
    },
    {
      score: 0.6473642,
      show: {
        id: 49752,
        url: "https://www.tvmaze.com/shows/49752/go-ahead",
        name: "Go Ahead",
        type: "Scripted",
        language: "Chinese",
        genres: ["Drama", "Comedy", "Romance"],
        status: "Ended",
        runtime: 60,
        averageRuntime: 60,
        premiered: "2020-08-10",
        ended: "2020-09-02",
        officialSite: null,
        schedule: {
          time: "20:00",
          days: [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday",
            "Sunday",
          ],
        },
        rating: { average: null },
        weight: 36,
        network: {
          id: 276,
          name: "Hunan TV",
          country: { name: "China", code: "CN", timezone: "Asia/Shanghai" },
          officialSite: null,
        },
        webChannel: null,
        dvdCountry: null,
        externals: { tvrage: null, thetvdb: 386014, imdb: "tt12477960" },
        image: {
          medium:
            "https://static.tvmaze.com/uploads/images/medium_portrait/400/1002139.jpg",
          original:
            "https://static.tvmaze.com/uploads/images/original_untouched/400/1002139.jpg",
        },
        summary:
          "<p>Three unrelated children who suffer different injuries in their original families, by chance, get together and become siblings.<br />The eldest brother Ling Xiao, the second brother He Zi Qiu, and the younger sister Li Jian Jian support each other and grow up together under the support of their two fathers. The history follows their childhoold, highschool years and adulthood.</p>",
        updated: 1647948798,
        _links: {
          self: { href: "https://api.tvmaze.com/shows/49752" },
          previousepisode: { href: "https://api.tvmaze.com/episodes/1915054" },
        },
      },
    },
    {
      score: 0.6450163,
      show: {
        id: 14372,
        url: "https://www.tvmaze.com/shows/14372/go-jetters",
        name: "Go Jetters",
        type: "Animation",
        language: "English",
        genres: ["Children"],
        status: "To Be Determined",
        runtime: 10,
        averageRuntime: 12,
        premiered: "2015-10-26",
        ended: null,
        officialSite: "http://www.bbc.co.uk/cbeebies/shows/go-jetters",
        schedule: {
          time: "16:50",
          days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        },
        rating: { average: null },
        weight: 35,
        network: {
          id: 458,
          name: "CBeebies",
          country: {
            name: "United Kingdom",
            code: "GB",
            timezone: "Europe/London",
          },
          officialSite: null,
        },
        webChannel: null,
        dvdCountry: null,
        externals: { tvrage: null, thetvdb: 302130, imdb: "tt5172468" },
        image: {
          medium:
            "https://static.tvmaze.com/uploads/images/medium_portrait/48/122045.jpg",
          original:
            "https://static.tvmaze.com/uploads/images/original_untouched/48/122045.jpg",
        },
        summary:
          "<p>A animated adventure series that follows Glitch and the grimbots.</p>",
        updated: 1617639838,
        _links: {
          self: { href: "https://api.tvmaze.com/shows/14372" },
          previousepisode: { href: "https://api.tvmaze.com/episodes/2062548" },
        },
      },
    },
    {
      score: 0.6380662,
      show: {
        id: 7031,
        url: "https://www.tvmaze.com/shows/7031/teddy-go",
        name: "Teddy Go!",
        type: "Scripted",
        language: "Japanese",
        genres: ["Drama", "Comedy", "Crime"],
        status: "Ended",
        runtime: 30,
        averageRuntime: 30,
        premiered: "2015-10-10",
        ended: "2015-10-31",
        officialSite: "http://www.fujitv.co.jp/en/d_15_22.html",
        schedule: { time: "23:40", days: ["Saturday"] },
        rating: { average: null },
        weight: 31,
        network: {
          id: 131,
          name: "Fuji TV",
          country: { name: "Japan", code: "JP", timezone: "Asia/Tokyo" },
          officialSite: null,
        },
        webChannel: null,
        dvdCountry: null,
        externals: { tvrage: null, thetvdb: 300824, imdb: null },
        image: {
          medium:
            "https://static.tvmaze.com/uploads/images/medium_portrait/26/65980.jpg",
          original:
            "https://static.tvmaze.com/uploads/images/original_untouched/26/65980.jpg",
        },
        summary:
          '<p>Yamase Kazuko is a 23-year-old part-time worker who recently got cheated and dumped by her boyfriend and also just lost her job - basically she feels she has reached the rock bottom in life. One day, she walks by a store and finds a teddy bear she fell in love with at first sight. She immediately buys and happily returns home with the teddy bear. The next morning, as she wakes up, what she saw in the mirror was a reflection of herself cuddling with … an tough-looking, middle-aged man! However apparently, no one can see him but Kazuko. He is actually the spirit of a man named Amano Yasuo, a detective who lost his life in the line of duty, hosted within the body of a teddy bear. With exchange conditions, the appealingly odd pair a job-less young female and middle-aged detective decide to work together to uncover the truth behind that criminal case that Amano pursued while he was alive.</p><p>(This show is based on an original work by Miaki Kato\'s novel entitled "Are You Teddy?".)</p>',
        updated: 1501188752,
        _links: {
          self: { href: "https://api.tvmaze.com/shows/7031" },
          previousepisode: { href: "https://api.tvmaze.com/episodes/414077" },
        },
      },
    },
  ],
};

const fetchData = {
  data: [
    {
      id: 1,
      url: "https://www.tvmaze.com/shows/1/under-the-dome",
      name: "Under the Dome",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Science-Fiction", "Thriller"],
      status: "Ended",
      runtime: 60,
      averageRuntime: 60,
      premiered: "2013-06-24",
      ended: "2015-09-10",
      officialSite: "http://www.cbs.com/shows/under-the-dome/",
      schedule: { time: "22:00", days: ["Thursday"] },
      rating: { average: 6.5 },
      weight: 99,
      network: {
        id: 2,
        name: "CBS",
        country: {
          name: "United States",
          code: "US",
          timezone: "America/New_York",
        },
        officialSite: "https://www.cbs.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 25988, thetvdb: 264492, imdb: "tt1553656" },
      image: {
        medium:
          "https://static.tvmaze.com/uploads/images/medium_portrait/81/202627.jpg",
        original:
          "https://static.tvmaze.com/uploads/images/original_untouched/81/202627.jpg",
      },
      summary:
        "<p><b>Under the Dome</b> is the story of a small town that is suddenly and inexplicably sealed off from the rest of the world by an enormous transparent dome. The town's inhabitants must deal with surviving the post-apocalyptic conditions while searching for answers about the dome, where it came from and if and when it will go away.</p>",
      updated: 1631010933,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/1" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/185054" },
      },
    },
    {
      id: 2,
      url: "https://www.tvmaze.com/shows/2/person-of-interest",
      name: "Person of Interest",
      type: "Scripted",
      language: "English",
      genres: ["Action", "Crime", "Science-Fiction"],
      status: "Ended",
      runtime: 60,
      averageRuntime: 60,
      premiered: "2011-09-22",
      ended: "2016-06-21",
      officialSite: "http://www.cbs.com/shows/person_of_interest/",
      schedule: { time: "22:00", days: ["Tuesday"] },
      rating: { average: 8.8 },
      weight: 99,
      network: {
        id: 2,
        name: "CBS",
        country: {
          name: "United States",
          code: "US",
          timezone: "America/New_York",
        },
        officialSite: "https://www.cbs.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 28376, thetvdb: 248742, imdb: "tt1839578" },
      image: {
        medium:
          "https://static.tvmaze.com/uploads/images/medium_portrait/163/407679.jpg",
        original:
          "https://static.tvmaze.com/uploads/images/original_untouched/163/407679.jpg",
      },
      summary:
        "<p>You are being watched. The government has a secret system, a machine that spies on you every hour of every day. I know because I built it. I designed the Machine to detect acts of terror but it sees everything. Violent crimes involving ordinary people. People like you. Crimes the government considered \"irrelevant\". They wouldn't act so I decided I would. But I needed a partner. Someone with the skills to intervene. Hunted by the authorities, we work in secret. You'll never find us. But victim or perpetrator, if your number is up, we'll find you.</p>",
      updated: 1678119582,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/2" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/659372" },
      },
    },
    {
      id: 3,
      url: "https://www.tvmaze.com/shows/3/bitten",
      name: "Bitten",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Horror", "Romance"],
      status: "Ended",
      runtime: 60,
      averageRuntime: 60,
      premiered: "2014-01-11",
      ended: "2016-04-15",
      officialSite: "http://bitten.space.ca/",
      schedule: { time: "22:00", days: ["Friday"] },
      rating: { average: 7.5 },
      weight: 96,
      network: {
        id: 7,
        name: "CTV Sci-Fi Channel",
        country: { name: "Canada", code: "CA", timezone: "America/Halifax" },
        officialSite: null,
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 34965, thetvdb: 269550, imdb: "tt2365946" },
      image: {
        medium:
          "https://static.tvmaze.com/uploads/images/medium_portrait/0/15.jpg",
        original:
          "https://static.tvmaze.com/uploads/images/original_untouched/0/15.jpg",
      },
      summary:
        '<p>Based on the critically acclaimed series of novels from Kelley Armstrong. Set in Toronto and upper New York State, <b>Bitten</b> follows the adventures of 28-year-old Elena Michaels, the world\'s only female werewolf. An orphan, Elena thought she finally found her "happily ever after" with her new love Clayton, until her life changed forever. With one small bite, the normal life she craved was taken away and she was left to survive life with the Pack.</p>',
      updated: 1665307838,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/3" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/631862" },
      },
    },
    {
      id: 4,
      url: "https://www.tvmaze.com/shows/4/arrow",
      name: "Arrow",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Action", "Science-Fiction"],
      status: "Ended",
      runtime: 60,
      averageRuntime: 60,
      premiered: "2012-10-10",
      ended: "2020-01-28",
      officialSite: "http://www.cwtv.com/shows/arrow",
      schedule: { time: "21:00", days: ["Tuesday"] },
      rating: { average: 7.4 },
      weight: 98,
      network: {
        id: 5,
        name: "The CW",
        country: {
          name: "United States",
          code: "US",
          timezone: "America/New_York",
        },
        officialSite: "https://www.cwtv.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 30715, thetvdb: 257655, imdb: "tt2193021" },
      image: {
        medium:
          "https://static.tvmaze.com/uploads/images/medium_portrait/213/534017.jpg",
        original:
          "https://static.tvmaze.com/uploads/images/original_untouched/213/534017.jpg",
      },
      summary:
        "<p>After a violent shipwreck, billionaire playboy Oliver Queen was missing and presumed dead for five years before being discovered alive on a remote island in the Pacific. He returned home to Starling City, welcomed by his devoted mother Moira, beloved sister Thea and former flame Laurel Lance. With the aid of his trusted chauffeur/bodyguard John Diggle, the computer-hacking skills of Felicity Smoak and the occasional, reluctant assistance of former police detective, now beat cop, Quentin Lance, Oliver has been waging a one-man war on crime.</p>",
      updated: 1671542677,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/4" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/1744752" },
      },
    },
    {
      id: 5,
      url: "https://www.tvmaze.com/shows/5/true-detective",
      name: "True Detective",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Crime", "Thriller"],
      status: "Running",
      runtime: 60,
      averageRuntime: 62,
      premiered: "2014-01-12",
      ended: null,
      officialSite: "http://www.hbo.com/true-detective",
      schedule: { time: "21:00", days: ["Sunday"] },
      rating: { average: 8.2 },
      weight: 99,
      network: {
        id: 8,
        name: "HBO",
        country: {
          name: "United States",
          code: "US",
          timezone: "America/New_York",
        },
        officialSite: "https://www.hbo.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 31369, thetvdb: 270633, imdb: "tt2356777" },
      image: {
        medium:
          "https://static.tvmaze.com/uploads/images/medium_portrait/445/1114021.jpg",
        original:
          "https://static.tvmaze.com/uploads/images/original_untouched/445/1114021.jpg",
      },
      summary:
        "<p>Touch darkness and darkness touches you back. <b>True Detective</b> centers on troubled cops and the investigations that drive them to the edge. Each season features a new cast and a new case.</p><p><i><b>True Detective</b></i> is an American anthology crime drama television series created and written by Nic Pizzolatto. </p>",
      updated: 1675608014,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/5" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/1590271" },
      },
    },
    {
      id: 6,
      url: "https://www.tvmaze.com/shows/6/the-100",
      name: "The 100",
      type: "Scripted",
      language: "English",
      genres: ["Action", "Adventure", "Science-Fiction"],
      status: "Ended",
      runtime: 60,
      averageRuntime: 60,
      premiered: "2014-03-19",
      ended: "2020-09-30",
      officialSite: "http://www.cwtv.com/shows/the-100/",
      schedule: { time: "20:00", days: ["Wednesday"] },
      rating: { average: 7.8 },
      weight: 97,
      network: {
        id: 5,
        name: "The CW",
        country: {
          name: "United States",
          code: "US",
          timezone: "America/New_York",
        },
        officialSite: "https://www.cwtv.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 34770, thetvdb: 268592, imdb: "tt2661044" },
      image: {
        medium:
          "https://static.tvmaze.com/uploads/images/medium_portrait/257/642675.jpg",
        original:
          "https://static.tvmaze.com/uploads/images/original_untouched/257/642675.jpg",
      },
      summary:
        "<p>Ninety-seven years ago, nuclear Armageddon decimated planet Earth, destroying civilization. The only survivors were the 400 inhabitants of 12 international space stations that were in orbit at the time. Three generations have been born in space, the survivors now number 4,000, and resources are running out on their dying \"Ark\" - the 12 stations now linked together and repurposed to keep the survivors alive. Draconian measures including capital punishment and population control are the order of the day, as the leaders of the Ark take ruthless steps to ensure their future, including secretly exiling a group of 100 juvenile prisoners to the Earth's surface to test whether it's habitable.</p>",
      updated: 1666564713,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/6" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/1913280" },
      },
    },
    {
      id: 7,
      url: "https://www.tvmaze.com/shows/7/homeland",
      name: "Homeland",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Thriller", "Espionage"],
      status: "Ended",
      runtime: 60,
      averageRuntime: 60,
      premiered: "2011-10-02",
      ended: "2020-04-26",
      officialSite: "http://www.sho.com/sho/homeland/home",
      schedule: { time: "21:00", days: ["Sunday"] },
      rating: { average: 8.2 },
      weight: 98,
      network: {
        id: 9,
        name: "Showtime",
        country: {
          name: "United States",
          code: "US",
          timezone: "America/New_York",
        },
        officialSite: "https://www.sho.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 27811, thetvdb: 247897, imdb: "tt1796960" },
      image: {
        medium:
          "https://static.tvmaze.com/uploads/images/medium_portrait/230/575652.jpg",
        original:
          "https://static.tvmaze.com/uploads/images/original_untouched/230/575652.jpg",
      },
      summary:
        "<p>The winner of 6 Emmy Awards including Outstanding Drama Series, <b>Homeland</b> is an edge-of-your-seat sensation. Marine Sergeant Nicholas Brody is both a decorated hero and a serious threat. CIA officer Carrie Mathison is tops in her field despite being bipolar. The delicate dance these two complex characters perform, built on lies, suspicion, and desire, is at the heart of this gripping, emotional thriller in which nothing short of the fate of our nation is at stake.</p>",
      updated: 1678119469,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/7" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/1801029" },
      },
    },
    {
      id: 8,
      url: "https://www.tvmaze.com/shows/8/glee",
      name: "Glee",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Music", "Romance"],
      status: "Ended",
      runtime: 60,
      averageRuntime: 60,
      premiered: "2009-05-19",
      ended: "2015-03-20",
      officialSite: "http://www.fox.com/glee",
      schedule: { time: "21:00", days: ["Friday"] },
      rating: { average: 6.6 },
      weight: 95,
      network: {
        id: 4,
        name: "FOX",
        country: {
          name: "United States",
          code: "US",
          timezone: "America/New_York",
        },
        officialSite: "https://www.fox.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 21704, thetvdb: 83610, imdb: "tt1327801" },
      image: {
        medium:
          "https://static.tvmaze.com/uploads/images/medium_portrait/0/73.jpg",
        original:
          "https://static.tvmaze.com/uploads/images/original_untouched/0/73.jpg",
      },
      summary:
        "<p><b>Glee </b>is a musical comedy about a group of ambitious and talented young adults in search of strength, acceptance and, ultimately, their voice.</p>",
      updated: 1679684177,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/8" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/142185" },
      },
    },
    {
      id: 9,
      url: "https://www.tvmaze.com/shows/9/revenge",
      name: "Revenge",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Thriller", "Mystery"],
      status: "Ended",
      runtime: 60,
      averageRuntime: 60,
      premiered: "2011-09-21",
      ended: "2015-05-10",
      officialSite: null,
      schedule: { time: "22:00", days: ["Sunday"] },
      rating: { average: 7.7 },
      weight: 95,
      network: {
        id: 3,
        name: "ABC",
        country: {
          name: "United States",
          code: "US",
          timezone: "America/New_York",
        },
        officialSite: "https://abc.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 28387, thetvdb: 248837, imdb: "tt1837642" },
      image: {
        medium:
          "https://static.tvmaze.com/uploads/images/medium_portrait/82/206879.jpg",
        original:
          "https://static.tvmaze.com/uploads/images/original_untouched/82/206879.jpg",
      },
      summary:
        "<p>This is not a story about forgiveness; <b>Revenge</b> is a show about retribution. Meet Emily Thorne, the newest resident of The Hamptons. When she was a little girl (and known as Amanda Clarke) her father, David Clarke, was framed for a horrific crime and subsequently sent to prison. While serving his time, the conspirators plotted and murdered David in order to prevent the truth from coming out. Emily is now back with a new identity and ready to take vengeance on the people that murdered her father and stole her childhood.</p>",
      updated: 1676115202,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/9" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/154117" },
      },
    },
    {
      id: 10,
      url: "https://www.tvmaze.com/shows/10/grimm",
      name: "Grimm",
      type: "Scripted",
      language: "English",
      genres: ["Drama", "Crime", "Supernatural"],
      status: "Ended",
      runtime: 60,
      averageRuntime: 60,
      premiered: "2011-10-28",
      ended: "2017-03-31",
      officialSite: "http://www.nbc.com/grimm",
      schedule: { time: "20:00", days: ["Friday"] },
      rating: { average: 8.4 },
      weight: 97,
      network: {
        id: 1,
        name: "NBC",
        country: {
          name: "United States",
          code: "US",
          timezone: "America/New_York",
        },
        officialSite: "https://www.nbc.com/",
      },
      webChannel: null,
      dvdCountry: null,
      externals: { tvrage: 28352, thetvdb: 248736, imdb: "tt1830617" },
      image: {
        medium:
          "https://static.tvmaze.com/uploads/images/medium_portrait/69/174906.jpg",
        original:
          "https://static.tvmaze.com/uploads/images/original_untouched/69/174906.jpg",
      },
      summary:
        "<p><b>Grimm </b>is a drama series inspired by the classic Grimm Brothers' Fairy Tales. After Portland homicide detective Nick Burkhardt discovers he's descended from an elite line of criminal profilers known as \"Grimms\", he increasingly finds his responsibilities as a detective at odds with his new responsibilities as a Grimm.</p>",
      updated: 1654168545,
      _links: {
        self: { href: "https://api.tvmaze.com/shows/10" },
        previousepisode: { href: "https://api.tvmaze.com/episodes/1009811" },
      },
    },
  ],
};

module.exports = {
  fetchData,
  searchData,
};
